title: <p align="center"> NGO Khoa Anh </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/cv2023.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/khoa-anh-ngo-5985a9156/">LinkedIn</a> |
  <a href="https://github.com/ngokhoaanh">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing MS degree in Data Science at Sorbonne University.
  <br><br>
  I am currently a Machine Learning Research Intern at Skim AI Technologies with a focus on NLP and Deep Learning research.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
